# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T:\amol\bit_bucket\rigtools\rigtools\ui\utilsUI\ui_wireTool.ui'
#
# Created: Tue Jun 06 14:26:26 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtWidgets

class Ui_wireToolWindow(object):
    def setupUi(self, wireToolWindow):
        wireToolWindow.setObjectName("wireToolWindow")
        wireToolWindow.resize(320, 368)
        self.centralwidget = QtWidgets.QWidget(wireToolWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.curve_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.curve_LE.setToolTip("")
        self.curve_LE.setWhatsThis("")
        self.curve_LE.setInputMask("")
        self.curve_LE.setObjectName("curve_LE")
        self.gridLayout.addWidget(self.curve_LE, 0, 1, 1, 1)
        self.curve_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.curve_btn.sizePolicy().hasHeightForWidth())
        self.curve_btn.setSizePolicy(sizePolicy)
        self.curve_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.curve_btn.setObjectName("curve_btn")
        self.gridLayout.addWidget(self.curve_btn, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.geo_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.geo_LE.setObjectName("geo_LE")
        self.gridLayout.addWidget(self.geo_LE, 1, 1, 1, 1)
        self.geo_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geo_btn.sizePolicy().hasHeightForWidth())
        self.geo_btn.setSizePolicy(sizePolicy)
        self.geo_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.geo_btn.setObjectName("geo_btn")
        self.gridLayout.addWidget(self.geo_btn, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.orientSample_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.orientSample_cb.setToolTip("")
        self.orientSample_cb.setWhatsThis("")
        self.orientSample_cb.setAccessibleName("")
        self.orientSample_cb.setAccessibleDescription("")
        self.orientSample_cb.setObjectName("orientSample_cb")
        self.verticalLayout.addWidget(self.orientSample_cb)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.orientSample_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.orientSample_LE.setObjectName("orientSample_LE")
        self.horizontalLayout.addWidget(self.orientSample_LE)
        self.orientSample_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orientSample_btn.sizePolicy().hasHeightForWidth())
        self.orientSample_btn.setSizePolicy(sizePolicy)
        self.orientSample_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.orientSample_btn.setObjectName("orientSample_btn")
        self.horizontalLayout.addWidget(self.orientSample_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setObjectName("create_btn")
        self.verticalLayout.addWidget(self.create_btn)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.deoformer_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.deoformer_LE.setObjectName("deoformer_LE")
        self.horizontalLayout_2.addWidget(self.deoformer_LE)
        self.deoformer_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deoformer_btn.sizePolicy().hasHeightForWidth())
        self.deoformer_btn.setSizePolicy(sizePolicy)
        self.deoformer_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.deoformer_btn.setObjectName("deoformer_btn")
        self.horizontalLayout_2.addWidget(self.deoformer_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.clean_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clean_btn.sizePolicy().hasHeightForWidth())
        self.clean_btn.setSizePolicy(sizePolicy)
        self.clean_btn.setObjectName("clean_btn")
        self.verticalLayout.addWidget(self.clean_btn)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        wireToolWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(wireToolWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        wireToolWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(wireToolWindow)
        self.statusBar.setObjectName("statusBar")
        wireToolWindow.setStatusBar(self.statusBar)
        self.actionExit = QtWidgets.QAction(wireToolWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(wireToolWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), wireToolWindow.close)
        QtCore.QMetaObject.connectSlotsByName(wireToolWindow)

    def retranslateUi(self, wireToolWindow):
        wireToolWindow.setWindowTitle(QtWidgets.QApplication.translate("wireToolWindow", "Wire Tool UI", None))
        self.label.setText(QtWidgets.QApplication.translate("wireToolWindow", "Curve:-", None))
        self.curve_LE.setStatusTip(QtWidgets.QApplication.translate("wireToolWindow", "load wire curve here", None))
        self.curve_LE.setPlaceholderText(QtWidgets.QApplication.translate("wireToolWindow", "WireCurve", None))
        self.curve_btn.setStatusTip(QtWidgets.QApplication.translate("wireToolWindow", "load wire", None))
        self.curve_btn.setText(QtWidgets.QApplication.translate("wireToolWindow", "<<", None))
        self.label_2.setText(QtWidgets.QApplication.translate("wireToolWindow", "Geometry:-", None))
        self.geo_LE.setStatusTip(QtWidgets.QApplication.translate("wireToolWindow", "load geometry here", None))
        self.geo_LE.setPlaceholderText(QtWidgets.QApplication.translate("wireToolWindow", "Geometry", None))
        self.geo_btn.setStatusTip(QtWidgets.QApplication.translate("wireToolWindow", "load geometry", None))
        self.geo_btn.setText(QtWidgets.QApplication.translate("wireToolWindow", "<<", None))
        self.orientSample_cb.setStatusTip(QtWidgets.QApplication.translate("wireToolWindow", "on for user defined orientation", None))
        self.orientSample_cb.setText(QtWidgets.QApplication.translate("wireToolWindow", "Orient Aim Sample:-", None))
        self.label_3.setText(QtWidgets.QApplication.translate("wireToolWindow", "Orient Sample:-", None))
        self.orientSample_LE.setStatusTip(QtWidgets.QApplication.translate("wireToolWindow", "orientation object, all sub controllers are aim to this object.", None))
        self.orientSample_LE.setPlaceholderText(QtWidgets.QApplication.translate("wireToolWindow", "Orientation Object", None))
        self.orientSample_btn.setStatusTip(QtWidgets.QApplication.translate("wireToolWindow", "load orientation sample object", None))
        self.orientSample_btn.setText(QtWidgets.QApplication.translate("wireToolWindow", "<<", None))
        self.create_btn.setStatusTip(QtWidgets.QApplication.translate("wireToolWindow", "create wire tool", None))
        self.create_btn.setText(QtWidgets.QApplication.translate("wireToolWindow", "Create Wire Tool", None))
        self.label_5.setText(QtWidgets.QApplication.translate("wireToolWindow", "Select Vertex To Clean Membership:-", None))
        self.label_4.setText(QtWidgets.QApplication.translate("wireToolWindow", "Wire Deformer:-", None))
        self.deoformer_LE.setStatusTip(QtWidgets.QApplication.translate("wireToolWindow", "load wire deformer to clean set membership", None))
        self.deoformer_LE.setPlaceholderText(QtWidgets.QApplication.translate("wireToolWindow", "Wire Deformer", None))
        self.deoformer_btn.setStatusTip(QtWidgets.QApplication.translate("wireToolWindow", "load wire deformer", None))
        self.deoformer_btn.setText(QtWidgets.QApplication.translate("wireToolWindow", "<<", None))
        self.clean_btn.setStatusTip(QtWidgets.QApplication.translate("wireToolWindow", "clean membership", None))
        self.clean_btn.setText(QtWidgets.QApplication.translate("wireToolWindow", "Clean Membership", None))
        self.menuMenu.setTitle(QtWidgets.QApplication.translate("wireToolWindow", "Menu", None))
        self.actionExit.setText(QtWidgets.QApplication.translate("wireToolWindow", "Exit", None))

