# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/bsw_programation/01_maya/Pipeline/rigtools/rigtools/ui/utilsUI/ui_wireTool.ui'
#
# Created: Thu Aug 24 16:52:16 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_wireToolWindow(object):
    def setupUi(self, wireToolWindow):
        wireToolWindow.setObjectName("wireToolWindow")
        wireToolWindow.resize(320, 368)
        self.centralwidget = QtGui.QWidget(wireToolWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.curve_LE = QtGui.QLineEdit(self.centralwidget)
        self.curve_LE.setToolTip("")
        self.curve_LE.setWhatsThis("")
        self.curve_LE.setInputMask("")
        self.curve_LE.setObjectName("curve_LE")
        self.gridLayout.addWidget(self.curve_LE, 0, 1, 1, 1)
        self.curve_btn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.curve_btn.sizePolicy().hasHeightForWidth())
        self.curve_btn.setSizePolicy(sizePolicy)
        self.curve_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.curve_btn.setObjectName("curve_btn")
        self.gridLayout.addWidget(self.curve_btn, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.geo_LE = QtGui.QLineEdit(self.centralwidget)
        self.geo_LE.setObjectName("geo_LE")
        self.gridLayout.addWidget(self.geo_LE, 1, 1, 1, 1)
        self.geo_btn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geo_btn.sizePolicy().hasHeightForWidth())
        self.geo_btn.setSizePolicy(sizePolicy)
        self.geo_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.geo_btn.setObjectName("geo_btn")
        self.gridLayout.addWidget(self.geo_btn, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.orientSample_cb = QtGui.QCheckBox(self.centralwidget)
        self.orientSample_cb.setToolTip("")
        self.orientSample_cb.setWhatsThis("")
        self.orientSample_cb.setAccessibleName("")
        self.orientSample_cb.setAccessibleDescription("")
        self.orientSample_cb.setObjectName("orientSample_cb")
        self.verticalLayout.addWidget(self.orientSample_cb)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.orientSample_LE = QtGui.QLineEdit(self.centralwidget)
        self.orientSample_LE.setObjectName("orientSample_LE")
        self.horizontalLayout.addWidget(self.orientSample_LE)
        self.orientSample_btn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orientSample_btn.sizePolicy().hasHeightForWidth())
        self.orientSample_btn.setSizePolicy(sizePolicy)
        self.orientSample_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.orientSample_btn.setObjectName("orientSample_btn")
        self.horizontalLayout.addWidget(self.orientSample_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.create_btn = QtGui.QPushButton(self.centralwidget)
        self.create_btn.setObjectName("create_btn")
        self.verticalLayout.addWidget(self.create_btn)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.deoformer_LE = QtGui.QLineEdit(self.centralwidget)
        self.deoformer_LE.setObjectName("deoformer_LE")
        self.horizontalLayout_2.addWidget(self.deoformer_LE)
        self.deoformer_btn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deoformer_btn.sizePolicy().hasHeightForWidth())
        self.deoformer_btn.setSizePolicy(sizePolicy)
        self.deoformer_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.deoformer_btn.setObjectName("deoformer_btn")
        self.horizontalLayout_2.addWidget(self.deoformer_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.clean_btn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clean_btn.sizePolicy().hasHeightForWidth())
        self.clean_btn.setSizePolicy(sizePolicy)
        self.clean_btn.setObjectName("clean_btn")
        self.verticalLayout.addWidget(self.clean_btn)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        wireToolWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(wireToolWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        wireToolWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(wireToolWindow)
        self.statusBar.setObjectName("statusBar")
        wireToolWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(wireToolWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(wireToolWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), wireToolWindow.close)
        QtCore.QMetaObject.connectSlotsByName(wireToolWindow)

    def retranslateUi(self, wireToolWindow):
        wireToolWindow.setWindowTitle(QtGui.QApplication.translate("wireToolWindow", "Wire Tool UI", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("wireToolWindow", "Curve:-", None, QtGui.QApplication.UnicodeUTF8))
        self.curve_LE.setStatusTip(QtGui.QApplication.translate("wireToolWindow", "load wire curve here", None, QtGui.QApplication.UnicodeUTF8))
        self.curve_LE.setPlaceholderText(QtGui.QApplication.translate("wireToolWindow", "WireCurve", None, QtGui.QApplication.UnicodeUTF8))
        self.curve_btn.setStatusTip(QtGui.QApplication.translate("wireToolWindow", "load wire", None, QtGui.QApplication.UnicodeUTF8))
        self.curve_btn.setText(QtGui.QApplication.translate("wireToolWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("wireToolWindow", "Geometry:-", None, QtGui.QApplication.UnicodeUTF8))
        self.geo_LE.setStatusTip(QtGui.QApplication.translate("wireToolWindow", "load geometry here", None, QtGui.QApplication.UnicodeUTF8))
        self.geo_LE.setPlaceholderText(QtGui.QApplication.translate("wireToolWindow", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.geo_btn.setStatusTip(QtGui.QApplication.translate("wireToolWindow", "load geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.geo_btn.setText(QtGui.QApplication.translate("wireToolWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.orientSample_cb.setStatusTip(QtGui.QApplication.translate("wireToolWindow", "on for user defined orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.orientSample_cb.setText(QtGui.QApplication.translate("wireToolWindow", "Orient Aim Sample:-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("wireToolWindow", "Orient Sample:-", None, QtGui.QApplication.UnicodeUTF8))
        self.orientSample_LE.setStatusTip(QtGui.QApplication.translate("wireToolWindow", "orientation object, all sub controllers are aim to this object.", None, QtGui.QApplication.UnicodeUTF8))
        self.orientSample_LE.setPlaceholderText(QtGui.QApplication.translate("wireToolWindow", "Orientation Object", None, QtGui.QApplication.UnicodeUTF8))
        self.orientSample_btn.setStatusTip(QtGui.QApplication.translate("wireToolWindow", "load orientation sample object", None, QtGui.QApplication.UnicodeUTF8))
        self.orientSample_btn.setText(QtGui.QApplication.translate("wireToolWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.create_btn.setStatusTip(QtGui.QApplication.translate("wireToolWindow", "create wire tool", None, QtGui.QApplication.UnicodeUTF8))
        self.create_btn.setText(QtGui.QApplication.translate("wireToolWindow", "Create Wire Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("wireToolWindow", "Select Vertex To Clean Membership:-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("wireToolWindow", "Wire Deformer:-", None, QtGui.QApplication.UnicodeUTF8))
        self.deoformer_LE.setStatusTip(QtGui.QApplication.translate("wireToolWindow", "load wire deformer to clean set membership", None, QtGui.QApplication.UnicodeUTF8))
        self.deoformer_LE.setPlaceholderText(QtGui.QApplication.translate("wireToolWindow", "Wire Deformer", None, QtGui.QApplication.UnicodeUTF8))
        self.deoformer_btn.setStatusTip(QtGui.QApplication.translate("wireToolWindow", "load wire deformer", None, QtGui.QApplication.UnicodeUTF8))
        self.deoformer_btn.setText(QtGui.QApplication.translate("wireToolWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.clean_btn.setStatusTip(QtGui.QApplication.translate("wireToolWindow", "clean membership", None, QtGui.QApplication.UnicodeUTF8))
        self.clean_btn.setText(QtGui.QApplication.translate("wireToolWindow", "Clean Membership", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("wireToolWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("wireToolWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

