# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T:\amol\bit_bucket\rigtools\rigtools\ui\aspToolsUI\ui_facial_tools.ui'
#
# Created: Wed May 24 16:40:23 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtWidgets

class Ui_FacialToolsWindow(object):
    def setupUi(self, FacialToolsWindow):
        FacialToolsWindow.setObjectName("FacialToolsWindow")
        FacialToolsWindow.resize(660, 505)
        self.centralwidget = QtWidgets.QWidget(FacialToolsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.faceGeo_btn = QtWidgets.QPushButton(self.centralwidget)
        self.faceGeo_btn.setObjectName("faceGeo_btn")
        self.gridLayout_3.addWidget(self.faceGeo_btn, 1, 1, 1, 1)
        self.namespaces_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.namespaces_LE.setObjectName("namespaces_LE")
        self.gridLayout_3.addWidget(self.namespaces_LE, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 3, 1, 1)
        self.faceGeoMainRig_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.faceGeoMainRig_LE.setObjectName("faceGeoMainRig_LE")
        self.gridLayout_3.addWidget(self.faceGeoMainRig_LE, 3, 0, 1, 1)
        self.faceGeoMainRig_btn = QtWidgets.QPushButton(self.centralwidget)
        self.faceGeoMainRig_btn.setObjectName("faceGeoMainRig_btn")
        self.gridLayout_3.addWidget(self.faceGeoMainRig_btn, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.faceGeo_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.faceGeo_LE.setObjectName("faceGeo_LE")
        self.gridLayout_3.addWidget(self.faceGeo_LE, 1, 0, 1, 1)
        self.faceGeoTopGroup_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.faceGeoTopGroup_LE.setObjectName("faceGeoTopGroup_LE")
        self.gridLayout_3.addWidget(self.faceGeoTopGroup_LE, 1, 3, 1, 1)
        self.faceGeoTopGroup_btn = QtWidgets.QPushButton(self.centralwidget)
        self.faceGeoTopGroup_btn.setObjectName("faceGeoTopGroup_btn")
        self.gridLayout_3.addWidget(self.faceGeoTopGroup_btn, 1, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.project_comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_comboBox.sizePolicy().hasHeightForWidth())
        self.project_comboBox.setSizePolicy(sizePolicy)
        self.project_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.project_comboBox.setObjectName("project_comboBox")
        self.gridLayout_5.addWidget(self.project_comboBox, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.export_tab = QtWidgets.QWidget()
        self.export_tab.setObjectName("export_tab")
        self.layoutWidget = QtWidgets.QWidget(self.export_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 27, 311, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.charName_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.charName_LE.setObjectName("charName_LE")
        self.horizontalLayout.addWidget(self.charName_LE)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.lip_rb = QtWidgets.QRadioButton(self.layoutWidget)
        self.lip_rb.setChecked(True)
        self.lip_rb.setObjectName("lip_rb")
        self.verticalLayout_2.addWidget(self.lip_rb)
        self.eyeBrow_rb = QtWidgets.QRadioButton(self.layoutWidget)
        self.eyeBrow_rb.setObjectName("eyeBrow_rb")
        self.verticalLayout_2.addWidget(self.eyeBrow_rb)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.export_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.export_btn.setObjectName("export_btn")
        self.horizontalLayout_2.addWidget(self.export_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.export_tab, "")
        self.export_tab1 = QtWidgets.QWidget()
        self.export_tab1.setObjectName("export_tab1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.export_tab1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.export_tab1)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.expSetups_LW = QtWidgets.QListWidget(self.export_tab1)
        self.expSetups_LW.setObjectName("expSetups_LW")
        self.gridLayout.addWidget(self.expSetups_LW, 2, 2, 1, 1)
        self.characters_LW = QtWidgets.QListWidget(self.export_tab1)
        self.characters_LW.setObjectName("characters_LW")
        self.gridLayout.addWidget(self.characters_LW, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.export_tab1)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.connect_btn = QtWidgets.QPushButton(self.export_tab1)
        self.connect_btn.setObjectName("connect_btn")
        self.gridLayout.addWidget(self.connect_btn, 3, 2, 1, 1)
        self.import_btn = QtWidgets.QPushButton(self.export_tab1)
        self.import_btn.setObjectName("import_btn")
        self.gridLayout.addWidget(self.import_btn, 3, 0, 1, 1)
        self.refresh_btn = QtWidgets.QPushButton(self.export_tab1)
        self.refresh_btn.setObjectName("refresh_btn")
        self.gridLayout.addWidget(self.refresh_btn, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.export_tab1, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        FacialToolsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FacialToolsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        FacialToolsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FacialToolsWindow)
        self.statusbar.setObjectName("statusbar")
        FacialToolsWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(FacialToolsWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(FacialToolsWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), FacialToolsWindow.close)
        QtCore.QMetaObject.connectSlotsByName(FacialToolsWindow)

    def retranslateUi(self, FacialToolsWindow):
        FacialToolsWindow.setWindowTitle(QtWidgets.QApplication.translate("FacialToolsWindow", "Facial Import Export Setups", None))
        self.faceGeo_btn.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "<<", None))
        self.namespaces_LE.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "XXX:", None))
        self.label_2.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Face Geometry Main Rig", None))
        self.label_4.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Namespaces", None))
        self.faceGeoMainRig_btn.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "<<", None))
        self.label_3.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Face Geometry Top Group", None))
        self.label.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Face Geometry", None))
        self.faceGeoTopGroup_btn.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "<<", None))
        self.label_8.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Project:-", None))
        self.label_5.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Character Name:- ", None))
        self.lip_rb.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Lip", None))
        self.eyeBrow_rb.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Eye Brow", None))
        self.export_btn.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Export", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.export_tab), QtWidgets.QApplication.translate("FacialToolsWindow", "Export", None))
        self.label_6.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Characters", None))
        self.label_7.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Exported Setups", None))
        self.connect_btn.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Connect", None))
        self.import_btn.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Import", None))
        self.refresh_btn.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Refresh", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.export_tab1), QtWidgets.QApplication.translate("FacialToolsWindow", "Import", None))
        self.menuMenu.setTitle(QtWidgets.QApplication.translate("FacialToolsWindow", "Menu", None))
        self.actionExit.setText(QtWidgets.QApplication.translate("FacialToolsWindow", "Exit", None))

