# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T:\amol\bit_bucket\rigtools\rigtools\ui\aspToolsUI\ui_facial_tools.ui'
#
# Created: Wed May 24 16:40:23 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FacialToolsWindow(object):
    def setupUi(self, FacialToolsWindow):
        FacialToolsWindow.setObjectName("FacialToolsWindow")
        FacialToolsWindow.resize(660, 505)
        self.centralwidget = QtGui.QWidget(FacialToolsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.faceGeo_btn = QtGui.QPushButton(self.centralwidget)
        self.faceGeo_btn.setObjectName("faceGeo_btn")
        self.gridLayout_3.addWidget(self.faceGeo_btn, 1, 1, 1, 1)
        self.namespaces_LE = QtGui.QLineEdit(self.centralwidget)
        self.namespaces_LE.setObjectName("namespaces_LE")
        self.gridLayout_3.addWidget(self.namespaces_LE, 3, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 3, 1, 1)
        self.faceGeoMainRig_LE = QtGui.QLineEdit(self.centralwidget)
        self.faceGeoMainRig_LE.setObjectName("faceGeoMainRig_LE")
        self.gridLayout_3.addWidget(self.faceGeoMainRig_LE, 3, 0, 1, 1)
        self.faceGeoMainRig_btn = QtGui.QPushButton(self.centralwidget)
        self.faceGeoMainRig_btn.setObjectName("faceGeoMainRig_btn")
        self.gridLayout_3.addWidget(self.faceGeoMainRig_btn, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.faceGeo_LE = QtGui.QLineEdit(self.centralwidget)
        self.faceGeo_LE.setObjectName("faceGeo_LE")
        self.gridLayout_3.addWidget(self.faceGeo_LE, 1, 0, 1, 1)
        self.faceGeoTopGroup_LE = QtGui.QLineEdit(self.centralwidget)
        self.faceGeoTopGroup_LE.setObjectName("faceGeoTopGroup_LE")
        self.gridLayout_3.addWidget(self.faceGeoTopGroup_LE, 1, 3, 1, 1)
        self.faceGeoTopGroup_btn = QtGui.QPushButton(self.centralwidget)
        self.faceGeoTopGroup_btn.setObjectName("faceGeoTopGroup_btn")
        self.gridLayout_3.addWidget(self.faceGeoTopGroup_btn, 1, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.project_comboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_comboBox.sizePolicy().hasHeightForWidth())
        self.project_comboBox.setSizePolicy(sizePolicy)
        self.project_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.project_comboBox.setObjectName("project_comboBox")
        self.gridLayout_5.addWidget(self.project_comboBox, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.export_tab = QtGui.QWidget()
        self.export_tab.setObjectName("export_tab")
        self.layoutWidget = QtGui.QWidget(self.export_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 27, 311, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.charName_LE = QtGui.QLineEdit(self.layoutWidget)
        self.charName_LE.setObjectName("charName_LE")
        self.horizontalLayout.addWidget(self.charName_LE)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.lip_rb = QtGui.QRadioButton(self.layoutWidget)
        self.lip_rb.setChecked(True)
        self.lip_rb.setObjectName("lip_rb")
        self.verticalLayout_2.addWidget(self.lip_rb)
        self.eyeBrow_rb = QtGui.QRadioButton(self.layoutWidget)
        self.eyeBrow_rb.setObjectName("eyeBrow_rb")
        self.verticalLayout_2.addWidget(self.eyeBrow_rb)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.export_btn = QtGui.QPushButton(self.layoutWidget)
        self.export_btn.setObjectName("export_btn")
        self.horizontalLayout_2.addWidget(self.export_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.export_tab, "")
        self.export_tab1 = QtGui.QWidget()
        self.export_tab1.setObjectName("export_tab1")
        self.gridLayout_2 = QtGui.QGridLayout(self.export_tab1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtGui.QLabel(self.export_tab1)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.expSetups_LW = QtGui.QListWidget(self.export_tab1)
        self.expSetups_LW.setObjectName("expSetups_LW")
        self.gridLayout.addWidget(self.expSetups_LW, 2, 2, 1, 1)
        self.characters_LW = QtGui.QListWidget(self.export_tab1)
        self.characters_LW.setObjectName("characters_LW")
        self.gridLayout.addWidget(self.characters_LW, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.export_tab1)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.connect_btn = QtGui.QPushButton(self.export_tab1)
        self.connect_btn.setObjectName("connect_btn")
        self.gridLayout.addWidget(self.connect_btn, 3, 2, 1, 1)
        self.import_btn = QtGui.QPushButton(self.export_tab1)
        self.import_btn.setObjectName("import_btn")
        self.gridLayout.addWidget(self.import_btn, 3, 0, 1, 1)
        self.refresh_btn = QtGui.QPushButton(self.export_tab1)
        self.refresh_btn.setObjectName("refresh_btn")
        self.gridLayout.addWidget(self.refresh_btn, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.export_tab1, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        FacialToolsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(FacialToolsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        FacialToolsWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(FacialToolsWindow)
        self.statusbar.setObjectName("statusbar")
        FacialToolsWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(FacialToolsWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(FacialToolsWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), FacialToolsWindow.close)
        QtCore.QMetaObject.connectSlotsByName(FacialToolsWindow)

    def retranslateUi(self, FacialToolsWindow):
        FacialToolsWindow.setWindowTitle(QtGui.QApplication.translate("FacialToolsWindow", "Facial Import Export Setups", None, QtGui.QApplication.UnicodeUTF8))
        self.faceGeo_btn.setText(QtGui.QApplication.translate("FacialToolsWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.namespaces_LE.setText(QtGui.QApplication.translate("FacialToolsWindow", "XXX:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FacialToolsWindow", "Face Geometry Main Rig", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FacialToolsWindow", "Namespaces", None, QtGui.QApplication.UnicodeUTF8))
        self.faceGeoMainRig_btn.setText(QtGui.QApplication.translate("FacialToolsWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FacialToolsWindow", "Face Geometry Top Group", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FacialToolsWindow", "Face Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.faceGeoTopGroup_btn.setText(QtGui.QApplication.translate("FacialToolsWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("FacialToolsWindow", "Project:-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FacialToolsWindow", "Character Name:- ", None, QtGui.QApplication.UnicodeUTF8))
        self.lip_rb.setText(QtGui.QApplication.translate("FacialToolsWindow", "Lip", None, QtGui.QApplication.UnicodeUTF8))
        self.eyeBrow_rb.setText(QtGui.QApplication.translate("FacialToolsWindow", "Eye Brow", None, QtGui.QApplication.UnicodeUTF8))
        self.export_btn.setText(QtGui.QApplication.translate("FacialToolsWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.export_tab), QtGui.QApplication.translate("FacialToolsWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FacialToolsWindow", "Characters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FacialToolsWindow", "Exported Setups", None, QtGui.QApplication.UnicodeUTF8))
        self.connect_btn.setText(QtGui.QApplication.translate("FacialToolsWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.import_btn.setText(QtGui.QApplication.translate("FacialToolsWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_btn.setText(QtGui.QApplication.translate("FacialToolsWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.export_tab1), QtGui.QApplication.translate("FacialToolsWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("FacialToolsWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("FacialToolsWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

