# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/bsw_programation/01_maya/Pipeline/rigtools/rigtools/ui/rigTools_ui.ui'
#
# Created: Tue Jul 11 13:19:42 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_rtMainWindow(object):
    def setupUi(self, rtMainWindow):
        rtMainWindow.setObjectName("rtMainWindow")
        rtMainWindow.resize(421, 889)
        self.centralwidget = QtWidgets.QWidget(rtMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 401, 848))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.joint_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.joint_groupBox.setGeometry(QtCore.QRect(10, 210, 381, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint_groupBox.sizePolicy().hasHeightForWidth())
        self.joint_groupBox.setSizePolicy(sizePolicy)
        self.joint_groupBox.setObjectName("joint_groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.joint_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.aimCons_groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.aimCons_groupBox.setObjectName("aimCons_groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.aimCons_groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 15, 341, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.layoutWidget1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.aimX_rb = QtWidgets.QRadioButton(self.frame)
        self.aimX_rb.setGeometry(QtCore.QRect(20, 13, 31, 17))
        self.aimX_rb.setChecked(True)
        self.aimX_rb.setObjectName("aimX_rb")
        self.aimY_rb = QtWidgets.QRadioButton(self.frame)
        self.aimY_rb.setGeometry(QtCore.QRect(60, 13, 31, 17))
        self.aimY_rb.setObjectName("aimY_rb")
        self.aimZ_rb = QtWidgets.QRadioButton(self.frame)
        self.aimZ_rb.setGeometry(QtCore.QRect(100, 13, 31, 17))
        self.aimZ_rb.setObjectName("aimZ_rb")
        self.horizontalLayout_3.addWidget(self.frame)
        self.line = QtWidgets.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.aimObX_rb = QtWidgets.QRadioButton(self.frame_2)
        self.aimObX_rb.setGeometry(QtCore.QRect(20, 13, 31, 17))
        self.aimObX_rb.setObjectName("aimObX_rb")
        self.aimObY_rb = QtWidgets.QRadioButton(self.frame_2)
        self.aimObY_rb.setGeometry(QtCore.QRect(60, 13, 31, 17))
        self.aimObY_rb.setObjectName("aimObY_rb")
        self.aimObZ_rb = QtWidgets.QRadioButton(self.frame_2)
        self.aimObZ_rb.setGeometry(QtCore.QRect(100, 13, 31, 17))
        self.aimObZ_rb.setChecked(True)
        self.aimObZ_rb.setObjectName("aimObZ_rb")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.orient_chain_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.orient_chain_btn.setObjectName("orient_chain_btn")
        self.horizontalLayout_4.addWidget(self.orient_chain_btn)
        self.aim_constraint_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.aim_constraint_btn.setObjectName("aim_constraint_btn")
        self.horizontalLayout_4.addWidget(self.aim_constraint_btn)
        self.aim_constraint_parent_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.aim_constraint_parent_btn.setObjectName("aim_constraint_parent_btn")
        self.horizontalLayout_4.addWidget(self.aim_constraint_parent_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.none_Orient_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.none_Orient_btn.setObjectName("none_Orient_btn")
        self.verticalLayout.addWidget(self.none_Orient_btn)
        self.verticalLayout_2.addWidget(self.aimCons_groupBox)
        self.multipleCons_groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multipleCons_groupBox.sizePolicy().hasHeightForWidth())
        self.multipleCons_groupBox.setSizePolicy(sizePolicy)
        self.multipleCons_groupBox.setMaximumSize(QtCore.QSize(16777215, 53))
        self.multipleCons_groupBox.setObjectName("multipleCons_groupBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.multipleCons_groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 342, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.maintainOffset_cb = QtWidgets.QCheckBox(self.layoutWidget2)
        self.maintainOffset_cb.setChecked(True)
        self.maintainOffset_cb.setObjectName("maintainOffset_cb")
        self.horizontalLayout_5.addWidget(self.maintainOffset_cb)
        self.point_constraint_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.point_constraint_btn.setObjectName("point_constraint_btn")
        self.horizontalLayout_5.addWidget(self.point_constraint_btn)
        self.orient_constraint_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.orient_constraint_btn.setObjectName("orient_constraint_btn")
        self.horizontalLayout_5.addWidget(self.orient_constraint_btn)
        self.parent_constraint_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.parent_constraint_btn.setObjectName("parent_constraint_btn")
        self.horizontalLayout_5.addWidget(self.parent_constraint_btn)
        self.verticalLayout_2.addWidget(self.multipleCons_groupBox)
        self.controller_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.controller_groupBox.setGeometry(QtCore.QRect(10, 480, 381, 101))
        self.controller_groupBox.setObjectName("controller_groupBox")
        self.layoutWidget3 = QtWidgets.QWidget(self.controller_groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 361, 70))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.negTrans_cb = QtWidgets.QCheckBox(self.layoutWidget3)
        self.negTrans_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.negTrans_cb.setObjectName("negTrans_cb")
        self.gridLayout.addWidget(self.negTrans_cb, 1, 2, 1, 1)
        self.FK_Proxy_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.FK_Proxy_btn.setObjectName("FK_Proxy_btn")
        self.gridLayout.addWidget(self.FK_Proxy_btn, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.FK_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.FK_btn.setObjectName("FK_btn")
        self.gridLayout.addWidget(self.FK_btn, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ctlAxis_X_rb = QtWidgets.QRadioButton(self.layoutWidget3)
        self.ctlAxis_X_rb.setChecked(True)
        self.ctlAxis_X_rb.setObjectName("ctlAxis_X_rb")
        self.horizontalLayout_6.addWidget(self.ctlAxis_X_rb)
        self.ctlAxis_Y_rb = QtWidgets.QRadioButton(self.layoutWidget3)
        self.ctlAxis_Y_rb.setObjectName("ctlAxis_Y_rb")
        self.horizontalLayout_6.addWidget(self.ctlAxis_Y_rb)
        self.ctlAxis_Z_rb = QtWidgets.QRadioButton(self.layoutWidget3)
        self.ctlAxis_Z_rb.setObjectName("ctlAxis_Z_rb")
        self.horizontalLayout_6.addWidget(self.ctlAxis_Z_rb)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(85, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.skin_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.skin_groupBox.setGeometry(QtCore.QRect(10, 580, 381, 51))
        self.skin_groupBox.setObjectName("skin_groupBox")
        self.layoutWidget4 = QtWidgets.QWidget(self.skin_groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 361, 25))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.select_Influence_object_btn = QtWidgets.QPushButton(self.layoutWidget4)
        self.select_Influence_object_btn.setObjectName("select_Influence_object_btn")
        self.horizontalLayout_7.addWidget(self.select_Influence_object_btn)
        self.copySkinOnMultipleObject_btn = QtWidgets.QPushButton(self.layoutWidget4)
        self.copySkinOnMultipleObject_btn.setObjectName("copySkinOnMultipleObject_btn")
        self.horizontalLayout_7.addWidget(self.copySkinOnMultipleObject_btn)
        self.ShiftShapeConnections_btn = QtWidgets.QPushButton(self.layoutWidget4)
        self.ShiftShapeConnections_btn.setObjectName("ShiftShapeConnections_btn")
        self.horizontalLayout_7.addWidget(self.ShiftShapeConnections_btn)
        self.advanceSkeleton_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.advanceSkeleton_groupBox.setGeometry(QtCore.QRect(10, 630, 381, 131))
        self.advanceSkeleton_groupBox.setObjectName("advanceSkeleton_groupBox")
        self.Follow_groupBox = QtWidgets.QGroupBox(self.advanceSkeleton_groupBox)
        self.Follow_groupBox.setGeometry(QtCore.QRect(10, 60, 361, 61))
        self.Follow_groupBox.setObjectName("Follow_groupBox")
        self.layoutWidget5 = QtWidgets.QWidget(self.Follow_groupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 20, 158, 25))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.IKArm_btn = QtWidgets.QPushButton(self.layoutWidget5)
        self.IKArm_btn.setObjectName("IKArm_btn")
        self.horizontalLayout_9.addWidget(self.IKArm_btn)
        self.PoleArm_btn = QtWidgets.QPushButton(self.layoutWidget5)
        self.PoleArm_btn.setObjectName("PoleArm_btn")
        self.horizontalLayout_9.addWidget(self.PoleArm_btn)
        self.layoutWidget6 = QtWidgets.QWidget(self.advanceSkeleton_groupBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 30, 361, 25))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.IK_Orient_btn = QtWidgets.QPushButton(self.layoutWidget6)
        self.IK_Orient_btn.setObjectName("IK_Orient_btn")
        self.horizontalLayout_8.addWidget(self.IK_Orient_btn)
        self.FingerSDK_btn = QtWidgets.QPushButton(self.layoutWidget6)
        self.FingerSDK_btn.setObjectName("FingerSDK_btn")
        self.horizontalLayout_8.addWidget(self.FingerSDK_btn)
        self.FK_in_IKSpine_btn = QtWidgets.QPushButton(self.layoutWidget6)
        self.FK_in_IKSpine_btn.setObjectName("FK_in_IKSpine_btn")
        self.horizontalLayout_8.addWidget(self.FK_in_IKSpine_btn)
        self.Hide_Extra_Joints_btn = QtWidgets.QPushButton(self.layoutWidget6)
        self.Hide_Extra_Joints_btn.setObjectName("Hide_Extra_Joints_btn")
        self.horizontalLayout_8.addWidget(self.Hide_Extra_Joints_btn)
        self.otherScript_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.otherScript_groupBox.setGeometry(QtCore.QRect(10, 770, 381, 61))
        self.otherScript_groupBox.setObjectName("otherScript_groupBox")
        self.WireTool_btn = QtWidgets.QPushButton(self.otherScript_groupBox)
        self.WireTool_btn.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.WireTool_btn.setObjectName("WireTool_btn")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 120, 381, 91))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget7.setGeometry(QtCore.QRect(11, 20, 361, 58))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.circleCtl_btn = QtWidgets.QPushButton(self.layoutWidget7)
        self.circleCtl_btn.setObjectName("circleCtl_btn")
        self.horizontalLayout_10.addWidget(self.circleCtl_btn)
        self.cubeCtl_btn = QtWidgets.QPushButton(self.layoutWidget7)
        self.cubeCtl_btn.setObjectName("cubeCtl_btn")
        self.horizontalLayout_10.addWidget(self.cubeCtl_btn)
        self.sphereCtl_btn = QtWidgets.QPushButton(self.layoutWidget7)
        self.sphereCtl_btn.setObjectName("sphereCtl_btn")
        self.horizontalLayout_10.addWidget(self.sphereCtl_btn)
        self.diamondCtl_btn = QtWidgets.QPushButton(self.layoutWidget7)
        self.diamondCtl_btn.setObjectName("diamondCtl_btn")
        self.horizontalLayout_10.addWidget(self.diamondCtl_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.noneColor_btn = QtWidgets.QPushButton(self.layoutWidget7)
        self.noneColor_btn.setObjectName("noneColor_btn")
        self.horizontalLayout.addWidget(self.noneColor_btn)
        self.blueColor_btn = QtWidgets.QPushButton(self.layoutWidget7)
        self.blueColor_btn.setText("")
        self.blueColor_btn.setObjectName("blueColor_btn")
        self.horizontalLayout.addWidget(self.blueColor_btn)
        self.redColor_btn = QtWidgets.QPushButton(self.layoutWidget7)
        self.redColor_btn.setText("")
        self.redColor_btn.setObjectName("redColor_btn")
        self.horizontalLayout.addWidget(self.redColor_btn)
        self.greenColor_btn = QtWidgets.QPushButton(self.layoutWidget7)
        self.greenColor_btn.setText("")
        self.greenColor_btn.setObjectName("greenColor_btn")
        self.horizontalLayout.addWidget(self.greenColor_btn)
        self.SkyBlueColor_btn = QtWidgets.QPushButton(self.layoutWidget7)
        self.SkyBlueColor_btn.setText("")
        self.SkyBlueColor_btn.setObjectName("SkyBlueColor_btn")
        self.horizontalLayout.addWidget(self.SkyBlueColor_btn)
        self.yellowColor_btn = QtWidgets.QPushButton(self.layoutWidget7)
        self.yellowColor_btn.setText("")
        self.yellowColor_btn.setObjectName("yellowColor_btn")
        self.horizontalLayout.addWidget(self.yellowColor_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.layoutWidget8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget8.setGeometry(QtCore.QRect(11, 7, 381, 111))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.sanity_check_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.sanity_check_btn.setMinimumSize(QtCore.QSize(75, 25))
        self.sanity_check_btn.setMaximumSize(QtCore.QSize(75, 25))
        self.sanity_check_btn.setObjectName("sanity_check_btn")
        self.horizontalLayout_11.addWidget(self.sanity_check_btn)
        self.Find_Duplicates_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.Find_Duplicates_btn.setMinimumSize(QtCore.QSize(74, 25))
        self.Find_Duplicates_btn.setMaximumSize(QtCore.QSize(100, 25))
        self.Find_Duplicates_btn.setObjectName("Find_Duplicates_btn")
        self.horizontalLayout_11.addWidget(self.Find_Duplicates_btn)
        self.Renamer_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.Renamer_btn.setMinimumSize(QtCore.QSize(74, 25))
        self.Renamer_btn.setMaximumSize(QtCore.QSize(100, 25))
        self.Renamer_btn.setObjectName("Renamer_btn")
        self.horizontalLayout_11.addWidget(self.Renamer_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.jointSel_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.jointSel_btn.setObjectName("jointSel_btn")
        self.horizontalLayout_12.addWidget(self.jointSel_btn)
        self.parent_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.parent_btn.setObjectName("parent_btn")
        self.horizontalLayout_12.addWidget(self.parent_btn)
        self.Zero_Out_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.Zero_Out_btn.setObjectName("Zero_Out_btn")
        self.horizontalLayout_12.addWidget(self.Zero_Out_btn)
        self.Select_All_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.Select_All_btn.setObjectName("Select_All_btn")
        self.horizontalLayout_12.addWidget(self.Select_All_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.matchPosition_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.matchPosition_btn.setObjectName("matchPosition_btn")
        self.horizontalLayout_13.addWidget(self.matchPosition_btn)
        self.matchOrientation_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.matchOrientation_btn.setObjectName("matchOrientation_btn")
        self.horizontalLayout_13.addWidget(self.matchOrientation_btn)
        self.matchBoth_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.matchBoth_btn.setObjectName("matchBoth_btn")
        self.horizontalLayout_13.addWidget(self.matchBoth_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        rtMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(rtMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        rtMainWindow.setMenuBar(self.menubar)
        self.actionFile = QtWidgets.QAction(rtMainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionExit = QtWidgets.QAction(rtMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionFile)
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(rtMainWindow)
        QtCore.QMetaObject.connectSlotsByName(rtMainWindow)

    def retranslateUi(self, rtMainWindow):
        rtMainWindow.setWindowTitle(QtWidgets.QApplication.translate("rtMainWindow", "Bioscopewala Rigging Tool", None, -1))
        self.joint_groupBox.setTitle(QtWidgets.QApplication.translate("rtMainWindow", "Joint", None, -1))
        self.aimCons_groupBox.setTitle(QtWidgets.QApplication.translate("rtMainWindow", "Aim Constraint And Orient two Joints and Hirarchy", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("rtMainWindow", "Aim Axis", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("rtMainWindow", "Object Up Axis", None, -1))
        self.aimX_rb.setText(QtWidgets.QApplication.translate("rtMainWindow", "X", None, -1))
        self.aimY_rb.setText(QtWidgets.QApplication.translate("rtMainWindow", "Y", None, -1))
        self.aimZ_rb.setText(QtWidgets.QApplication.translate("rtMainWindow", "Z", None, -1))
        self.aimObX_rb.setText(QtWidgets.QApplication.translate("rtMainWindow", "X", None, -1))
        self.aimObY_rb.setText(QtWidgets.QApplication.translate("rtMainWindow", "Y", None, -1))
        self.aimObZ_rb.setText(QtWidgets.QApplication.translate("rtMainWindow", "Z", None, -1))
        self.orient_chain_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "orient_chain", None, -1))
        self.aim_constraint_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "aim_constraint", None, -1))
        self.aim_constraint_parent_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "aim_constraint_parent", None, -1))
        self.none_Orient_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "None Joint Orientation", None, -1))
        self.multipleCons_groupBox.setTitle(QtWidgets.QApplication.translate("rtMainWindow", "Constraint Multiple Object", None, -1))
        self.maintainOffset_cb.setText(QtWidgets.QApplication.translate("rtMainWindow", "Maintain Offset", None, -1))
        self.point_constraint_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "point const", None, -1))
        self.orient_constraint_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "orient const", None, -1))
        self.parent_constraint_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "parent const", None, -1))
        self.controller_groupBox.setTitle(QtWidgets.QApplication.translate("rtMainWindow", "FK Controller", None, -1))
        self.negTrans_cb.setText(QtWidgets.QApplication.translate("rtMainWindow", "Neg Trans", None, -1))
        self.FK_Proxy_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "FK_Proxy", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("rtMainWindow", "Axis", None, -1))
        self.FK_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "FK", None, -1))
        self.ctlAxis_X_rb.setText(QtWidgets.QApplication.translate("rtMainWindow", "X", None, -1))
        self.ctlAxis_Y_rb.setText(QtWidgets.QApplication.translate("rtMainWindow", "Y", None, -1))
        self.ctlAxis_Z_rb.setText(QtWidgets.QApplication.translate("rtMainWindow", "Z", None, -1))
        self.skin_groupBox.setTitle(QtWidgets.QApplication.translate("rtMainWindow", "Skin", None, -1))
        self.select_Influence_object_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "select_Influence_object", None, -1))
        self.copySkinOnMultipleObject_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Copy Skin UI", None, -1))
        self.ShiftShapeConnections_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Shift Shape Connections", None, -1))
        self.advanceSkeleton_groupBox.setTitle(QtWidgets.QApplication.translate("rtMainWindow", "Advance Skeleton Scripts", None, -1))
        self.Follow_groupBox.setTitle(QtWidgets.QApplication.translate("rtMainWindow", "Follow", None, -1))
        self.IKArm_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "IKArm", None, -1))
        self.PoleArm_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "PoleArm", None, -1))
        self.IK_Orient_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "IK_Orient", None, -1))
        self.FingerSDK_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "FingerSDK", None, -1))
        self.FK_in_IKSpine_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "FK_in_IKSpine", None, -1))
        self.Hide_Extra_Joints_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Hide_Extra_Joints", None, -1))
        self.otherScript_groupBox.setTitle(QtWidgets.QApplication.translate("rtMainWindow", "Other Script", None, -1))
        self.WireTool_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "WireTool", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("rtMainWindow", "Controller", None, -1))
        self.circleCtl_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Circle", None, -1))
        self.cubeCtl_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Cube", None, -1))
        self.sphereCtl_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Sphere", None, -1))
        self.diamondCtl_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Diamond", None, -1))
        self.noneColor_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "none", None, -1))
        self.sanity_check_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Sanity Check", None, -1))
        self.Find_Duplicates_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Find Duplicates", None, -1))
        self.Renamer_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Renamer", None, -1))
        self.jointSel_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Joint On Sel", None, -1))
        self.parent_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Parent", None, -1))
        self.Zero_Out_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Zero Out", None, -1))
        self.Select_All_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Select All", None, -1))
        self.matchPosition_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Match Position", None, -1))
        self.matchOrientation_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Match Orientation", None, -1))
        self.matchBoth_btn.setText(QtWidgets.QApplication.translate("rtMainWindow", "Match Both", None, -1))
        self.menuMenu.setTitle(QtWidgets.QApplication.translate("rtMainWindow", "Menu", None, -1))
        self.actionFile.setText(QtWidgets.QApplication.translate("rtMainWindow", "File", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("rtMainWindow", "Exit", None, -1))

