# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S:/bsw_programation/01_maya/Pipeline/rigtools/rigtools/ui/rigTools_ui.ui'
#
# Created: Mon Sep 18 14:01:47 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_rtMainWindow(object):
    def setupUi(self, rtMainWindow):
        rtMainWindow.setObjectName("rtMainWindow")
        rtMainWindow.resize(418, 910)
        self.centralwidget = QtGui.QWidget(rtMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 398, 869))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.joint_groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.joint_groupBox.setGeometry(QtCore.QRect(10, 240, 381, 271))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint_groupBox.sizePolicy().hasHeightForWidth())
        self.joint_groupBox.setSizePolicy(sizePolicy)
        self.joint_groupBox.setObjectName("joint_groupBox")
        self.layoutWidget = QtGui.QWidget(self.joint_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.aimCons_groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.aimCons_groupBox.setObjectName("aimCons_groupBox")
        self.layoutWidget1 = QtGui.QWidget(self.aimCons_groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(5, 15, 351, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtGui.QFrame(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.aimX_rb = QtGui.QRadioButton(self.frame)
        self.aimX_rb.setGeometry(QtCore.QRect(20, 13, 31, 17))
        self.aimX_rb.setChecked(True)
        self.aimX_rb.setObjectName("aimX_rb")
        self.aimY_rb = QtGui.QRadioButton(self.frame)
        self.aimY_rb.setGeometry(QtCore.QRect(60, 13, 31, 17))
        self.aimY_rb.setObjectName("aimY_rb")
        self.aimZ_rb = QtGui.QRadioButton(self.frame)
        self.aimZ_rb.setGeometry(QtCore.QRect(100, 13, 31, 17))
        self.aimZ_rb.setObjectName("aimZ_rb")
        self.horizontalLayout_3.addWidget(self.frame)
        self.line = QtGui.QFrame(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMaximumSize(QtCore.QSize(16777215, 23))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.frame_2 = QtGui.QFrame(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.aimObX_rb = QtGui.QRadioButton(self.frame_2)
        self.aimObX_rb.setGeometry(QtCore.QRect(20, 13, 31, 17))
        self.aimObX_rb.setObjectName("aimObX_rb")
        self.aimObY_rb = QtGui.QRadioButton(self.frame_2)
        self.aimObY_rb.setGeometry(QtCore.QRect(60, 13, 31, 17))
        self.aimObY_rb.setObjectName("aimObY_rb")
        self.aimObZ_rb = QtGui.QRadioButton(self.frame_2)
        self.aimObZ_rb.setGeometry(QtCore.QRect(100, 13, 31, 17))
        self.aimObZ_rb.setChecked(True)
        self.aimObZ_rb.setObjectName("aimObZ_rb")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.orient_chain_btn = QtGui.QPushButton(self.layoutWidget1)
        self.orient_chain_btn.setObjectName("orient_chain_btn")
        self.horizontalLayout_4.addWidget(self.orient_chain_btn)
        self.aim_constraint_btn = QtGui.QPushButton(self.layoutWidget1)
        self.aim_constraint_btn.setObjectName("aim_constraint_btn")
        self.horizontalLayout_4.addWidget(self.aim_constraint_btn)
        self.aim_constraint_parent_btn = QtGui.QPushButton(self.layoutWidget1)
        self.aim_constraint_parent_btn.setObjectName("aim_constraint_parent_btn")
        self.horizontalLayout_4.addWidget(self.aim_constraint_parent_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.none_Orient_btn = QtGui.QPushButton(self.layoutWidget1)
        self.none_Orient_btn.setObjectName("none_Orient_btn")
        self.verticalLayout.addWidget(self.none_Orient_btn)
        self.verticalLayout_2.addWidget(self.aimCons_groupBox)
        self.multipleCons_groupBox = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multipleCons_groupBox.sizePolicy().hasHeightForWidth())
        self.multipleCons_groupBox.setSizePolicy(sizePolicy)
        self.multipleCons_groupBox.setMaximumSize(QtCore.QSize(16777215, 53))
        self.multipleCons_groupBox.setObjectName("multipleCons_groupBox")
        self.layoutWidget2 = QtGui.QWidget(self.multipleCons_groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 352, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.maintainOffset_cb = QtGui.QCheckBox(self.layoutWidget2)
        self.maintainOffset_cb.setMinimumSize(QtCore.QSize(107, 0))
        self.maintainOffset_cb.setChecked(True)
        self.maintainOffset_cb.setObjectName("maintainOffset_cb")
        self.horizontalLayout_5.addWidget(self.maintainOffset_cb)
        self.point_constraint_btn = QtGui.QPushButton(self.layoutWidget2)
        self.point_constraint_btn.setObjectName("point_constraint_btn")
        self.horizontalLayout_5.addWidget(self.point_constraint_btn)
        self.orient_constraint_btn = QtGui.QPushButton(self.layoutWidget2)
        self.orient_constraint_btn.setObjectName("orient_constraint_btn")
        self.horizontalLayout_5.addWidget(self.orient_constraint_btn)
        self.parent_constraint_btn = QtGui.QPushButton(self.layoutWidget2)
        self.parent_constraint_btn.setObjectName("parent_constraint_btn")
        self.horizontalLayout_5.addWidget(self.parent_constraint_btn)
        self.verticalLayout_2.addWidget(self.multipleCons_groupBox)
        self.controller_groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.controller_groupBox.setGeometry(QtCore.QRect(10, 510, 381, 101))
        self.controller_groupBox.setObjectName("controller_groupBox")
        self.layoutWidget3 = QtGui.QWidget(self.controller_groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 361, 70))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.negTrans_cb = QtGui.QCheckBox(self.layoutWidget3)
        self.negTrans_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.negTrans_cb.setObjectName("negTrans_cb")
        self.gridLayout.addWidget(self.negTrans_cb, 1, 2, 1, 1)
        self.FK_Proxy_btn = QtGui.QPushButton(self.layoutWidget3)
        self.FK_Proxy_btn.setObjectName("FK_Proxy_btn")
        self.gridLayout.addWidget(self.FK_Proxy_btn, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.FK_btn = QtGui.QPushButton(self.layoutWidget3)
        self.FK_btn.setObjectName("FK_btn")
        self.gridLayout.addWidget(self.FK_btn, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ctlAxis_X_rb = QtGui.QRadioButton(self.layoutWidget3)
        self.ctlAxis_X_rb.setChecked(True)
        self.ctlAxis_X_rb.setObjectName("ctlAxis_X_rb")
        self.horizontalLayout_6.addWidget(self.ctlAxis_X_rb)
        self.ctlAxis_Y_rb = QtGui.QRadioButton(self.layoutWidget3)
        self.ctlAxis_Y_rb.setObjectName("ctlAxis_Y_rb")
        self.horizontalLayout_6.addWidget(self.ctlAxis_Y_rb)
        self.ctlAxis_Z_rb = QtGui.QRadioButton(self.layoutWidget3)
        self.ctlAxis_Z_rb.setObjectName("ctlAxis_Z_rb")
        self.horizontalLayout_6.addWidget(self.ctlAxis_Z_rb)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(85, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.skin_groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.skin_groupBox.setGeometry(QtCore.QRect(10, 610, 381, 51))
        self.skin_groupBox.setObjectName("skin_groupBox")
        self.layoutWidget4 = QtGui.QWidget(self.skin_groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 361, 25))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.select_Influence_object_btn = QtGui.QPushButton(self.layoutWidget4)
        self.select_Influence_object_btn.setObjectName("select_Influence_object_btn")
        self.horizontalLayout_7.addWidget(self.select_Influence_object_btn)
        self.copySkinOnMultipleObject_btn = QtGui.QPushButton(self.layoutWidget4)
        self.copySkinOnMultipleObject_btn.setObjectName("copySkinOnMultipleObject_btn")
        self.horizontalLayout_7.addWidget(self.copySkinOnMultipleObject_btn)
        self.ShiftShapeConnections_btn = QtGui.QPushButton(self.layoutWidget4)
        self.ShiftShapeConnections_btn.setObjectName("ShiftShapeConnections_btn")
        self.horizontalLayout_7.addWidget(self.ShiftShapeConnections_btn)
        self.advanceSkeleton_groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.advanceSkeleton_groupBox.setGeometry(QtCore.QRect(10, 660, 381, 131))
        self.advanceSkeleton_groupBox.setObjectName("advanceSkeleton_groupBox")
        self.Follow_groupBox = QtGui.QGroupBox(self.advanceSkeleton_groupBox)
        self.Follow_groupBox.setGeometry(QtCore.QRect(10, 60, 361, 61))
        self.Follow_groupBox.setObjectName("Follow_groupBox")
        self.layoutWidget5 = QtGui.QWidget(self.Follow_groupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 20, 158, 25))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.IKArm_btn = QtGui.QPushButton(self.layoutWidget5)
        self.IKArm_btn.setObjectName("IKArm_btn")
        self.horizontalLayout_9.addWidget(self.IKArm_btn)
        self.PoleArm_btn = QtGui.QPushButton(self.layoutWidget5)
        self.PoleArm_btn.setObjectName("PoleArm_btn")
        self.horizontalLayout_9.addWidget(self.PoleArm_btn)
        self.addPlacement_btn = QtGui.QPushButton(self.Follow_groupBox)
        self.addPlacement_btn.setGeometry(QtCore.QRect(190, 21, 81, 23))
        self.addPlacement_btn.setObjectName("addPlacement_btn")
        self.addVis_btn = QtGui.QPushButton(self.Follow_groupBox)
        self.addVis_btn.setGeometry(QtCore.QRect(280, 21, 75, 23))
        self.addVis_btn.setObjectName("addVis_btn")
        self.layoutWidget6 = QtGui.QWidget(self.advanceSkeleton_groupBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 30, 361, 25))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.IK_Orient_btn = QtGui.QPushButton(self.layoutWidget6)
        self.IK_Orient_btn.setObjectName("IK_Orient_btn")
        self.horizontalLayout_8.addWidget(self.IK_Orient_btn)
        self.FingerSDK_btn = QtGui.QPushButton(self.layoutWidget6)
        self.FingerSDK_btn.setObjectName("FingerSDK_btn")
        self.horizontalLayout_8.addWidget(self.FingerSDK_btn)
        self.FK_in_IKSpine_btn = QtGui.QPushButton(self.layoutWidget6)
        self.FK_in_IKSpine_btn.setObjectName("FK_in_IKSpine_btn")
        self.horizontalLayout_8.addWidget(self.FK_in_IKSpine_btn)
        self.Hide_Extra_Joints_btn = QtGui.QPushButton(self.layoutWidget6)
        self.Hide_Extra_Joints_btn.setObjectName("Hide_Extra_Joints_btn")
        self.horizontalLayout_8.addWidget(self.Hide_Extra_Joints_btn)
        self.otherScript_groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.otherScript_groupBox.setGeometry(QtCore.QRect(10, 800, 381, 61))
        self.otherScript_groupBox.setObjectName("otherScript_groupBox")
        self.WireTool_btn = QtGui.QPushButton(self.otherScript_groupBox)
        self.WireTool_btn.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.WireTool_btn.setObjectName("WireTool_btn")
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 120, 381, 111))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget7 = QtGui.QWidget(self.groupBox)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 80, 361, 25))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.noneColor_btn = QtGui.QPushButton(self.layoutWidget7)
        self.noneColor_btn.setObjectName("noneColor_btn")
        self.horizontalLayout.addWidget(self.noneColor_btn)
        self.blueColor_btn = QtGui.QPushButton(self.layoutWidget7)
        self.blueColor_btn.setText("")
        self.blueColor_btn.setObjectName("blueColor_btn")
        self.horizontalLayout.addWidget(self.blueColor_btn)
        self.redColor_btn = QtGui.QPushButton(self.layoutWidget7)
        self.redColor_btn.setText("")
        self.redColor_btn.setObjectName("redColor_btn")
        self.horizontalLayout.addWidget(self.redColor_btn)
        self.greenColor_btn = QtGui.QPushButton(self.layoutWidget7)
        self.greenColor_btn.setText("")
        self.greenColor_btn.setObjectName("greenColor_btn")
        self.horizontalLayout.addWidget(self.greenColor_btn)
        self.SkyBlueColor_btn = QtGui.QPushButton(self.layoutWidget7)
        self.SkyBlueColor_btn.setText("")
        self.SkyBlueColor_btn.setObjectName("SkyBlueColor_btn")
        self.horizontalLayout.addWidget(self.SkyBlueColor_btn)
        self.yellowColor_btn = QtGui.QPushButton(self.layoutWidget7)
        self.yellowColor_btn.setText("")
        self.yellowColor_btn.setObjectName("yellowColor_btn")
        self.horizontalLayout.addWidget(self.yellowColor_btn)
        self.layoutWidget8 = QtGui.QWidget(self.groupBox)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 20, 361, 25))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.shapeReplace_cb = QtGui.QCheckBox(self.layoutWidget8)
        self.shapeReplace_cb.setObjectName("shapeReplace_cb")
        self.horizontalLayout_10.addWidget(self.shapeReplace_cb)
        self.circleCtl_btn = QtGui.QPushButton(self.layoutWidget8)
        self.circleCtl_btn.setObjectName("circleCtl_btn")
        self.horizontalLayout_10.addWidget(self.circleCtl_btn)
        self.cubeCtl_btn = QtGui.QPushButton(self.layoutWidget8)
        self.cubeCtl_btn.setObjectName("cubeCtl_btn")
        self.horizontalLayout_10.addWidget(self.cubeCtl_btn)
        self.sphereCtl_btn = QtGui.QPushButton(self.layoutWidget8)
        self.sphereCtl_btn.setObjectName("sphereCtl_btn")
        self.horizontalLayout_10.addWidget(self.sphereCtl_btn)
        self.layoutWidget9 = QtGui.QWidget(self.groupBox)
        self.layoutWidget9.setGeometry(QtCore.QRect(10, 50, 401, 25))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.diamondCtl_btn = QtGui.QPushButton(self.layoutWidget9)
        self.diamondCtl_btn.setObjectName("diamondCtl_btn")
        self.horizontalLayout_14.addWidget(self.diamondCtl_btn)
        self.coneCtl_btn = QtGui.QPushButton(self.layoutWidget9)
        self.coneCtl_btn.setObjectName("coneCtl_btn")
        self.horizontalLayout_14.addWidget(self.coneCtl_btn)
        self.arrrowBallCtl_btn = QtGui.QPushButton(self.layoutWidget9)
        self.arrrowBallCtl_btn.setObjectName("arrrowBallCtl_btn")
        self.horizontalLayout_14.addWidget(self.arrrowBallCtl_btn)
        self.arrow1Ctl_btn = QtGui.QPushButton(self.layoutWidget9)
        self.arrow1Ctl_btn.setObjectName("arrow1Ctl_btn")
        self.horizontalLayout_14.addWidget(self.arrow1Ctl_btn)
        self.arrow4Ctl_btn = QtGui.QPushButton(self.layoutWidget9)
        self.arrow4Ctl_btn.setObjectName("arrow4Ctl_btn")
        self.horizontalLayout_14.addWidget(self.arrow4Ctl_btn)
        self.layoutWidget10 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget10.setGeometry(QtCore.QRect(11, 7, 381, 111))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.sanity_check_btn = QtGui.QPushButton(self.layoutWidget10)
        self.sanity_check_btn.setMinimumSize(QtCore.QSize(75, 25))
        self.sanity_check_btn.setMaximumSize(QtCore.QSize(75, 25))
        self.sanity_check_btn.setObjectName("sanity_check_btn")
        self.horizontalLayout_11.addWidget(self.sanity_check_btn)
        self.Find_Duplicates_btn = QtGui.QPushButton(self.layoutWidget10)
        self.Find_Duplicates_btn.setMinimumSize(QtCore.QSize(74, 25))
        self.Find_Duplicates_btn.setMaximumSize(QtCore.QSize(100, 25))
        self.Find_Duplicates_btn.setObjectName("Find_Duplicates_btn")
        self.horizontalLayout_11.addWidget(self.Find_Duplicates_btn)
        self.Renamer_btn = QtGui.QPushButton(self.layoutWidget10)
        self.Renamer_btn.setMinimumSize(QtCore.QSize(74, 25))
        self.Renamer_btn.setMaximumSize(QtCore.QSize(100, 25))
        self.Renamer_btn.setObjectName("Renamer_btn")
        self.horizontalLayout_11.addWidget(self.Renamer_btn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.jointSel_btn = QtGui.QPushButton(self.layoutWidget10)
        self.jointSel_btn.setObjectName("jointSel_btn")
        self.horizontalLayout_12.addWidget(self.jointSel_btn)
        self.parent_btn = QtGui.QPushButton(self.layoutWidget10)
        self.parent_btn.setObjectName("parent_btn")
        self.horizontalLayout_12.addWidget(self.parent_btn)
        self.Zero_Out_btn = QtGui.QPushButton(self.layoutWidget10)
        self.Zero_Out_btn.setObjectName("Zero_Out_btn")
        self.horizontalLayout_12.addWidget(self.Zero_Out_btn)
        self.Select_All_btn = QtGui.QPushButton(self.layoutWidget10)
        self.Select_All_btn.setObjectName("Select_All_btn")
        self.horizontalLayout_12.addWidget(self.Select_All_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.matchPosition_btn = QtGui.QPushButton(self.layoutWidget10)
        self.matchPosition_btn.setObjectName("matchPosition_btn")
        self.horizontalLayout_13.addWidget(self.matchPosition_btn)
        self.matchOrientation_btn = QtGui.QPushButton(self.layoutWidget10)
        self.matchOrientation_btn.setObjectName("matchOrientation_btn")
        self.horizontalLayout_13.addWidget(self.matchOrientation_btn)
        self.matchBoth_btn = QtGui.QPushButton(self.layoutWidget10)
        self.matchBoth_btn.setObjectName("matchBoth_btn")
        self.horizontalLayout_13.addWidget(self.matchBoth_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        rtMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(rtMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 418, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        rtMainWindow.setMenuBar(self.menubar)
        self.actionFile = QtGui.QAction(rtMainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionExit = QtGui.QAction(rtMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(rtMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuMenu.addAction(self.actionFile)
        self.menuMenu.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(rtMainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), rtMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(rtMainWindow)

    def retranslateUi(self, rtMainWindow):
        rtMainWindow.setWindowTitle(QtGui.QApplication.translate("rtMainWindow", "Bioscopewala Rigging Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.joint_groupBox.setTitle(QtGui.QApplication.translate("rtMainWindow", "Joint", None, QtGui.QApplication.UnicodeUTF8))
        self.aimCons_groupBox.setTitle(QtGui.QApplication.translate("rtMainWindow", "Aim Constraint And Orient two Joints and Hirarchy", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("rtMainWindow", "Aim Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("rtMainWindow", "Object Up Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.aimX_rb.setText(QtGui.QApplication.translate("rtMainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.aimY_rb.setText(QtGui.QApplication.translate("rtMainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.aimZ_rb.setText(QtGui.QApplication.translate("rtMainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.aimObX_rb.setText(QtGui.QApplication.translate("rtMainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.aimObY_rb.setText(QtGui.QApplication.translate("rtMainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.aimObZ_rb.setText(QtGui.QApplication.translate("rtMainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.orient_chain_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Orient Chain", None, QtGui.QApplication.UnicodeUTF8))
        self.aim_constraint_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Aim Constraint", None, QtGui.QApplication.UnicodeUTF8))
        self.aim_constraint_parent_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Aim Constraint Parent", None, QtGui.QApplication.UnicodeUTF8))
        self.none_Orient_btn.setText(QtGui.QApplication.translate("rtMainWindow", "None Joint Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.multipleCons_groupBox.setTitle(QtGui.QApplication.translate("rtMainWindow", "Constraint Multiple Object", None, QtGui.QApplication.UnicodeUTF8))
        self.maintainOffset_cb.setText(QtGui.QApplication.translate("rtMainWindow", "Maintain Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.point_constraint_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Point Const", None, QtGui.QApplication.UnicodeUTF8))
        self.orient_constraint_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Orient Const", None, QtGui.QApplication.UnicodeUTF8))
        self.parent_constraint_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Parent Const", None, QtGui.QApplication.UnicodeUTF8))
        self.controller_groupBox.setTitle(QtGui.QApplication.translate("rtMainWindow", "FK Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.negTrans_cb.setText(QtGui.QApplication.translate("rtMainWindow", "Neg Trans", None, QtGui.QApplication.UnicodeUTF8))
        self.FK_Proxy_btn.setText(QtGui.QApplication.translate("rtMainWindow", "FK Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("rtMainWindow", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.FK_btn.setText(QtGui.QApplication.translate("rtMainWindow", "FK", None, QtGui.QApplication.UnicodeUTF8))
        self.ctlAxis_X_rb.setText(QtGui.QApplication.translate("rtMainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.ctlAxis_Y_rb.setText(QtGui.QApplication.translate("rtMainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.ctlAxis_Z_rb.setText(QtGui.QApplication.translate("rtMainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.skin_groupBox.setTitle(QtGui.QApplication.translate("rtMainWindow", "Skin", None, QtGui.QApplication.UnicodeUTF8))
        self.select_Influence_object_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Select Influence Object", None, QtGui.QApplication.UnicodeUTF8))
        self.copySkinOnMultipleObject_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Copy Skin UI", None, QtGui.QApplication.UnicodeUTF8))
        self.ShiftShapeConnections_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Shift Shape Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.advanceSkeleton_groupBox.setTitle(QtGui.QApplication.translate("rtMainWindow", "Advance Skeleton Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.Follow_groupBox.setTitle(QtGui.QApplication.translate("rtMainWindow", "Follow", None, QtGui.QApplication.UnicodeUTF8))
        self.IKArm_btn.setText(QtGui.QApplication.translate("rtMainWindow", "IKArm", None, QtGui.QApplication.UnicodeUTF8))
        self.PoleArm_btn.setText(QtGui.QApplication.translate("rtMainWindow", "PoleArm", None, QtGui.QApplication.UnicodeUTF8))
        self.addPlacement_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Add Placement", None, QtGui.QApplication.UnicodeUTF8))
        self.addVis_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Add Vis", None, QtGui.QApplication.UnicodeUTF8))
        self.IK_Orient_btn.setText(QtGui.QApplication.translate("rtMainWindow", "IK Orient", None, QtGui.QApplication.UnicodeUTF8))
        self.FingerSDK_btn.setText(QtGui.QApplication.translate("rtMainWindow", "FingerSDK", None, QtGui.QApplication.UnicodeUTF8))
        self.FK_in_IKSpine_btn.setText(QtGui.QApplication.translate("rtMainWindow", "FK in IKSpine", None, QtGui.QApplication.UnicodeUTF8))
        self.Hide_Extra_Joints_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Hide Extra Joints", None, QtGui.QApplication.UnicodeUTF8))
        self.otherScript_groupBox.setTitle(QtGui.QApplication.translate("rtMainWindow", "Other Script", None, QtGui.QApplication.UnicodeUTF8))
        self.WireTool_btn.setText(QtGui.QApplication.translate("rtMainWindow", "WireTool", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("rtMainWindow", "Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.noneColor_btn.setText(QtGui.QApplication.translate("rtMainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.shapeReplace_cb.setText(QtGui.QApplication.translate("rtMainWindow", "Shape Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.circleCtl_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.cubeCtl_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Cube", None, QtGui.QApplication.UnicodeUTF8))
        self.sphereCtl_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Sphere", None, QtGui.QApplication.UnicodeUTF8))
        self.diamondCtl_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Diamond", None, QtGui.QApplication.UnicodeUTF8))
        self.coneCtl_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Cone", None, QtGui.QApplication.UnicodeUTF8))
        self.arrrowBallCtl_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Arrow Ball", None, QtGui.QApplication.UnicodeUTF8))
        self.arrow1Ctl_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Arrow 1", None, QtGui.QApplication.UnicodeUTF8))
        self.arrow4Ctl_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Arrow 4", None, QtGui.QApplication.UnicodeUTF8))
        self.sanity_check_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Sanity Check", None, QtGui.QApplication.UnicodeUTF8))
        self.Find_Duplicates_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Find Duplicates", None, QtGui.QApplication.UnicodeUTF8))
        self.Renamer_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Renamer", None, QtGui.QApplication.UnicodeUTF8))
        self.jointSel_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Joint On Sel", None, QtGui.QApplication.UnicodeUTF8))
        self.parent_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Parent", None, QtGui.QApplication.UnicodeUTF8))
        self.Zero_Out_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Zero Out", None, QtGui.QApplication.UnicodeUTF8))
        self.Select_All_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.matchPosition_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Match Position", None, QtGui.QApplication.UnicodeUTF8))
        self.matchOrientation_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Match Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.matchBoth_btn.setText(QtGui.QApplication.translate("rtMainWindow", "Match Both", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("rtMainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("rtMainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFile.setText(QtGui.QApplication.translate("rtMainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("rtMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("rtMainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

