# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T:\amol\bit_bucket\rigtools\rigtools\ui\extUI\ui_shiftInpOut.ui'
#
# Created: Thu Mar 23 12:43:01 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtWidgets


class Ui_ShiftInpOutConnWindow(object):
    def setupUi(self, ShiftInpOutConnWindow):
        ShiftInpOutConnWindow.setObjectName("ShiftInpOutConnWindow")
        ShiftInpOutConnWindow.resize(491, 300)
        self.centralwidget = QtWidgets.QWidget(ShiftInpOutConnWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.newShapeCreate_btn = QtWidgets.QPushButton(self.centralwidget)
        self.newShapeCreate_btn.setObjectName("newShapeCreate_btn")
        self.gridLayout_4.addWidget(self.newShapeCreate_btn, 1, 2, 1, 1)
        self.newShpName_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.newShpName_LE.setObjectName("newShpName_LE")
        self.gridLayout_4.addWidget(self.newShpName_LE, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.shiftConnections_btn = QtWidgets.QPushButton(self.centralwidget)
        self.shiftConnections_btn.setObjectName("shiftConnections_btn")
        self.gridLayout_2.addWidget(self.shiftConnections_btn, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 4, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.srcOutLd_btn = QtWidgets.QPushButton(self.centralwidget)
        self.srcOutLd_btn.setObjectName("srcOutLd_btn")
        self.gridLayout.addWidget(self.srcOutLd_btn, 4, 3, 1, 1)
        self.destInpLd_btn = QtWidgets.QPushButton(self.centralwidget)
        self.destInpLd_btn.setObjectName("destInpLd_btn")
        self.gridLayout.addWidget(self.destInpLd_btn, 7, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 8, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.destOut_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.destOut_LE.setObjectName("destOut_LE")
        self.gridLayout.addWidget(self.destOut_LE, 8, 2, 1, 1)
        self.destInp_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.destInp_LE.setObjectName("destInp_LE")
        self.gridLayout.addWidget(self.destInp_LE, 7, 2, 1, 1)
        self.destOutLd_btn = QtWidgets.QPushButton(self.centralwidget)
        self.destOutLd_btn.setObjectName("destOutLd_btn")
        self.gridLayout.addWidget(self.destOutLd_btn, 8, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.srcInp_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.srcInp_LE.setObjectName("srcInp_LE")
        self.gridLayout.addWidget(self.srcInp_LE, 1, 2, 1, 1)
        self.srcOut_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.srcOut_LE.setObjectName("srcOut_LE")
        self.gridLayout.addWidget(self.srcOut_LE, 4, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 3, 1, 1)
        self.srcInpLd_btn = QtWidgets.QPushButton(self.centralwidget)
        self.srcInpLd_btn.setObjectName("srcInpLd_btn")
        self.gridLayout.addWidget(self.srcInpLd_btn, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 1, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 3, 0, 1, 1)
        ShiftInpOutConnWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ShiftInpOutConnWindow)
        QtCore.QMetaObject.connectSlotsByName(ShiftInpOutConnWindow)

    def retranslateUi(self, ShiftInpOutConnWindow):
        ShiftInpOutConnWindow.setWindowTitle(
            QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "Shift Mesh Input Output Connections", None))
        self.newShapeCreate_btn.setText(
            QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "Create", None))
        self.label_7.setText(
            QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "Create New Shapes on Selected Transform.", None))
        self.label_5.setText(QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "Enter New Shape Name:-", None))
        self.shiftConnections_btn.setText(
            QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "Shift Connections", None))
        self.srcOutLd_btn.setText(
            QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "<<", None))
        self.destInpLd_btn.setText(
            QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "<<", None))
        self.label_4.setText(
            QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "Destination Output Shape:-", None))
        self.label_3.setText(
            QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "Destination Input Shape:-", None))
        self.destOutLd_btn.setText(
            QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "<<", None))
        self.label.setText(QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "Source Output Shape:-", None))
        self.label_6.setText(QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "Get Source Shapes", None))
        self.srcInpLd_btn.setText(
            QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "<<", None))
        self.label_2.setText(QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "Source Input Shape:-", None))
        self.label_8.setText(QtWidgets.QApplication.translate("ShiftInpOutConnWindow", "Get Destination Shapes", None))
